### ISSUE TITLE
Kong v2 Support

### ISSUE THREAD

**Issue by harsimranb** [TravelNest/kong-authorization-opa#2]
Does this support Kong v2?

**Comment by maxTN** [comment]
Hi @harsimranb, I haven't tested it against anything beyond `v1.13` and I haven't checked if the internal Kong libraries have changed. Could be worth a try - sorry I'm not of more use at this time! If you give it a go and it's successful - please let us know!

**Comment by carnei-ro** [comment]
Hello @harsimranb , I have created a version based on this plugin and aws-lambda. Check if it works to you: github.com:carnei-ro/kong-authorization-opa.git
